apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: {{ .Release.Name }}-metrics
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "argo-rollouts.labels" . | nindent 4 }}
  {{- range $label_name, $label_value := .Values.platform_labels }}
    {{ $label_name }}: {{ $label_value }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "argo-rollouts.labels" . | nindent 4 }}
